disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Davud Kaplan"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "SampleDescription"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/davudk"

["params.author"]
name = "Davud Kaplan"
headline = "Passionate about using technology, education, and faith to create meaningful impact."
bio = "Sharing reflections and ideas at the intersection of purpose, productivity, and service."
