import type { Metadata } from 'next'
import './globals.scss'
import 'prismjs/themes/prism-tomorrow.min.css';

import { Navigation } from './components/Navigation'
import { Footer } from './components/Footer'

export const metadata: Metadata = {
  title: 'Davud\'s blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className="max-w-2xl min-h-screen mx-auto px-3 md:px-0 py-2 flex flex-col">
          <Navigation />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
