import type { Metadata } from 'next'
import { ReactNode } from 'react';
import './globals.scss'
import 'prismjs/themes/prism-tomorrow.min.css';

import { Navigation } from './components/Navigation'
import { Footer } from './components/Footer'
import { Posts } from '@/app/posts';

export const metadata: Metadata = {
  title: 'Davud\'s blog',
  description: 'Generated by create next app',
}

export interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  return (
    <html lang="en" className="overflow-y-scroll">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link href="https://fonts.googleapis.com/css2?family=Shantell+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />
      </head>
      <body className="dark:bg-neutral-800 dark:text-slate-100">
        <div className="max-w-2xl min-h-screen mx-auto px-3 md:px-0 py-2 flex flex-col">
          <Navigation posts={Posts} />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
